# device
device_type: camera
camera_name: camera
serial_number: ""
usb_port: ""
device_num: 1
upgrade_firmware: ""
preset_firmware_path: ""
load_config_json_file_path: ""
export_config_json_file_path: ""
uvc_backend: libuvc
connection_delay: 10
publish_tf: true
tf_publish_rate: 0.0
ir_info_url: ""
color_info_url: ""

# device_misc
device_access_mode: Default
exposure_range_mode: default
log_level: none
log_file_name: ""
enable_publish_extrinsic: false
enable_d2c_viewer: false
disparity_to_depth_mode: ""
align_mode: SW
align_target_stream: COLOR
diagnostic_period: 1.0
device_preset: Dual Color Streams
retry_on_usb3_detection_failure: false
enable_sync_host_time: true
time_sync_period: 6.0
time_domain: global
config_file_path: ""
enable_heartbeat: false
gmsl_trigger_fps: 3000
enable_gmsl_trigger: false
disparity_range_mode: -1
disparity_search_offset: -1
disparity_offset_config: false
offset_index0: -1
offset_index1: -1
frame_aggregate_mode: ANY
interleave_ae_mode: hdr
interleave_frame_enable: false
interleave_skip_enable: false
interleave_skip_index: 1
show_fps_enable: false

# color
enable_color: false
color_width: 0
color_height: 0
color_fps: 0
color_format: ANY
color_qos: default
color_camera_info_qos: default
color_rotation: -1
color_flip: false
color_mirror: false
enable_color_decimation_filter: false
color_decimation_filter_scale: -1

# left_color
enable_left_color: true
left_color_width: 0
left_color_height: 0
left_color_fps: 0
left_color_format: ANY
left_color_qos: default
left_color_camera_info_qos: default
left_color_rotation: -1
left_color_flip: false
left_color_mirror: false
enable_left_color_decimation_filter: false
left_color_decimation_filter_scale: -1

# right_color
enable_right_color: true
right_color_width: 0
right_color_height: 0
right_color_fps: 0
right_color_format: ANY
right_color_qos: default
right_color_camera_info_qos: default
right_color_rotation: -1
right_color_flip: false
right_color_mirror: false
enable_right_color_decimation_filter: false
right_color_decimation_filter_scale: -1

# color_common
enable_color_auto_exposure_priority: false
enable_color_auto_white_balance: true
enable_color_auto_exposure: true
color_ae_roi_left: -1
color_ae_roi_right: -1
color_ae_roi_top: -1
color_ae_roi_bottom: -1
color_exposure: -1
color_gain: -1
color_white_balance: -1
color_ae_max_exposure: -1
color_brightness: -1
color_sharpness: -1
color_gamma: -1
color_saturation: -1
color_contrast: -1
color_hue: -1
color_backlight_compensation: -1
color_powerline_freq: ""
color_denoising_level: -1
enable_color_undistortion: false

# hdr_params
hdr_index1_depth_exposure: 1
hdr_index1_depth_gain: 16
hdr_index1_ir_brightness: 30
hdr_index1_ir_ae_max_exposure: 30458
hdr_index0_depth_exposure: 7500
hdr_index0_depth_gain: 16
hdr_index0_ir_brightness: 90
hdr_index0_ir_ae_max_exposure: 30458

# publishers and transports
left_color.image_raw.enable_pub_plugins: ["image_transport/compressed", "image_transport/raw", "image_transport/theora"]
right_color.image_raw.enable_pub_plugins: ["image_transport/compressed", "image_transport/raw", "image_transport/theora"]

# In dual color mode, it is not recommended to change the following parameters
# depth
enable_depth: false
depth_width: 0
depth_height: 0
depth_fps: 0
depth_format: ANY
depth_qos: default
depth_camera_info_qos: default
enable_depth_auto_exposure_priority: false
depth_precision: ""
depth_rotation: -1
depth_flip: false
depth_mirror: false
depth_ae_roi_left: -1
depth_ae_roi_right: -1
depth_ae_roi_top: -1
depth_ae_roi_bottom: -1
mean_intensity_set_point: -1
enable_depth_scale: false
enable_decimation_filter: false
decimation_filter_scale: -1
enable_hdr_merge: false
hdr_merge_exposure_1: -1
hdr_merge_gain_1: -1
hdr_merge_exposure_2: -1
hdr_merge_gain_2: -1
enable_sequence_id_filter: false
sequence_id_filter_id: -1
enable_threshold_filter: false
threshold_filter_max: -1
threshold_filter_min: -1
enable_hardware_noise_removal_filter: false
hardware_noise_removal_filter_threshold: -1.0
enable_noise_removal_filter: false
noise_removal_filter_min_diff: 256
noise_removal_filter_max_size: 80
enable_spatial_filter: false
spatial_filter_alpha: -1.0
spatial_filter_diff_threshold: -1
spatial_filter_magnitude: -1
spatial_filter_radius: -1
enable_temporal_filter: false
temporal_filter_diff_threshold: -1.0
temporal_filter_weight: -1.0
enable_disparity_to_depth: false
hole_filling_filter_mode: ""
enable_hole_filling_filter: false
enable_spatial_fast_filter: false
spatial_fast_filter_radius: -1
enable_spatial_moderate_filter: false
spatial_moderate_filter_diff_threshold: -1
spatial_moderate_filter_magnitude: -1
spatial_moderate_filter_radius: -1

# point_cloud
depth_registration: false
point_cloud_qos: default
enable_point_cloud: false
point_cloud_decimation_filter_factor: 1
enable_colored_point_cloud: false
cloud_frame_id: ""
ordered_pc: false

# ldp
enable_ldp: true
ldp_power_level: -1

# left_ir
enable_left_ir: false
left_ir_width: 0
left_ir_height: 0
left_ir_fps: 0
left_ir_format: ANY
left_ir_qos: default
left_ir_camera_info_qos: default
left_ir_rotation: -1
left_ir_flip: false
left_ir_mirror: false
enable_left_ir_sequence_id_filter: false
left_ir_sequence_id_filter_id: -1

# right_ir
enable_right_ir: false
right_ir_width: 0
right_ir_height: 0
right_ir_fps: 0
right_ir_format: ANY
right_ir_qos: default
right_ir_camera_info_qos: default
right_ir_rotation: -1
right_ir_flip: false
right_ir_mirror: false
enable_right_ir_sequence_id_filter: false
right_ir_sequence_id_filter_id: -1

# ir_common
enable_ir_auto_exposure: false
ir_exposure: -1
ir_gain: -1
ir_ae_max_exposure: -1
ir_brightness: -1

# imu
enable_sync_output_accel_gyro: false
enable_accel: false
enable_accel_data_correction: false
accel_rate: 200hz
accel_range: 4g
enable_gyro: false
enable_gyro_data_correction: false
gyro_rate: 200hz
gyro_range: 1000dps
linear_accel_cov: 0.01
angular_vel_cov: 0.01

depth_delay_us: 0
color_delay_us: 0
trigger2image_delay_us: 0
trigger_out_delay_us: 0
trigger_out_enabled: true
software_trigger_enabled: true
frames_per_trigger: 2
software_trigger_period: 33

enable_ptp_config: false
enable_frame_sync: true

noise_removal_filter_min_diff: 256
noise_removal_filter_max_size: 80

# laser_params
laser_index1_laser_control: 0
laser_index1_depth_exposure: 3000
laser_index1_depth_gain: 16
laser_index1_ir_brightness: 60
laser_index1_ir_ae_max_exposure: 17000
laser_index0_laser_control: 1
laser_index0_depth_exposure: 3000
laser_index0_depth_gain: 16
laser_index0_ir_brightness: 60
laser_index0_ir_ae_max_exposure: 30000

